name: Johnny Portfolio
favicon: null
layout_spectrum: 0.6291529119480401
typography_spectrum: 0.6197474333457649
title: Johnny Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bea07e'
    - '#5b2f12'
    - '#765b3e'
    - '#eddfad'
  brandStrength: 0.6061948598362505
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
